#!/bin/zsh

assert() {
       if [[ "$2" != "$3" ]]; then
       	   echo "Failure: $1\n\tExpected: $3\n\tReceived: $2"
	   ERR=1
       fi
}

assert 'unigrams' "$(./ngram <(echo 'a b c'))" "$(echo 'a\nb\nc')"
assert 'unigrams stdin' "$(echo 'a b c' | ./ngram)" "$(echo 'a\nb\nc')"
assert 'unigrams multifile' "$(./ngram <(echo 'a') <(echo 'b c'))" "$(echo 'a\nb\nc')"
assert 'left pad bigrams' "$(./ngram -l1 -n2 <(echo 'a\nb\nc'))" "$(echo '_ a\n_ b\n_ c')"
assert 'custom left pad bigrams' "$(./ngram -l1 -n2 -px <(echo 'a\nb\nc'))" "$(echo 'x a\nx b\nx c')"
assert 'right pad bigrams' "$(./ngram -r1 -n2 <(echo 'a\nb\nc'))" "$(echo 'a _\nb _\nc _')"
assert 'skipgrams' "$(./ngram -s1 -n2 <(echo 'a b c'))" "$(echo 'a b\na c\nb c')"
assert 'skipgrams long' "$(./ngram -s2 -n3 <(echo 'a b c d e'))" "$(echo 'a b c\na b d\na b e\na c d\na c e\na d e\nb c d\nb c e\nb d e\nc d e')"

[[ -z "$ERR" ]] && echo "All Tests Pass"
exit "$ERR"
